title: Gregory Morris # your name (or website title) here
logo: "/images/logo-cropped.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  13 years of healthcare experience with 8 years in technology. I have demonstrated project leadership, customer development, and system thinking that have led to an over $4M yearly increase in revenue. 
  <br><br>
  <a href="https://www.linkedin.com/in/gregorywaynemorris/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
